plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.1.36'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java {
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

sourceSets {
    main {
        java {
            srcDir 'src/main/java'
            include 'moriyashiine/nycto/common/NyctoNeoForge.java'
            include 'moriyashiine/nycto/neoforge/**'
        }
        resources {
            srcDir 'src/main/resources'
            srcDir 'src/main/generated'
            exclude 'data/c/**'
            exclude 'data/enchancement/**'
            exclude 'data/minecraft/tags/timeline/**'
            exclude 'data/nycto/anthropophagy/**'
            exclude 'data/nycto/tags/enchantment/**'
            exclude 'data/nycto/tags/nycto/**'
            exclude 'data/nycto/tags/worldgen/biome/spawns_vampires.json'
            exclude 'data/nycto/timeline/**'
        }
    }
}

repositories {
    maven {
        name = 'NeoForge'
        url = 'https://maven.neoforged.net/releases'
    }
    mavenCentral()
}

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        workingDirectory project.layout.projectDirectory.dir('run').dir(name)
        modSource project.sourceSets.main
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        argument '--nogui'
    }

    data {
        arguments.addAll '--mod', project.mod_id,
                '--all',
                '--output', file('src/main/generated').getAbsolutePath(),
                '--existing', file('src/main/resources').getAbsolutePath()
    }
}

configurations {
    localRuntime
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
}

tasks.withType(ProcessResources).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    includeEmptyDirs = false
    exclude 'nycto.mixins.json'

    def replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

jar {
    from('LICENSE') {
        rename { "${it}_${project.name}" }
    }
}

tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.matching { it.name.endsWith('DownloadAssets') }.configureEach {
    enabled = false
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
}
