# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true
# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache = false
# Game Properties
minecraft_version = 26.2
loader_version = 0.19.3
loom_version = 1.17-SNAPSHOT
# Mod Properties
mod_id = nycto
mod_name = Nycto
mod_description = Adds vampires (and later werewolves), and allows you turn into or hunt them
version = 26.2-b5
group = moriyashiine.nycto
# Common Dependencies
cardinal_components_version = 8.0.1
midnightlib_version = 1.9.3+26.2
fabric_api_version = 0.158.0+26.2
strawberrylib_version = 26.2-r3
anthropophagy_version = 26.2-r3
hearty_meals_version = 26.2-r3
superb_steeds_version = 26.2-r2
# Chenille
release_type = beta
modrinth_id = tnTEDxIj
curseforge_id = 1230789
curseforge_versions = 26.2
