# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# NeoForge / Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.233
loader_version_range=[1,)

# Mod
mod_id=nycto
mod_name=Nycto
mod_license=All Rights Reserved
mod_version=1.21.1-neoforge-b0
mod_group_id=moriyashiine
mod_authors=MoriyaShiine, cybercat5555
mod_description=Adds vampires and later werewolves, and allows you to turn into or hunt them.
